version: '3'

vars:
  REPOSITORY: gtonic/pptx-mcp

tasks:
  build:
    cmds:
      - docker build --no-cache -t pptx-mcp .

  run:
    cmds:
      - docker run -it --rm -p 8081:8081 $(docker build -q .)

  publish:
    cmds:
      - docker buildx build . --push --platform linux/amd64,linux/arm64 --tag {{.REPOSITORY}}
